services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: 
      context: .
      dockerfile: ./dockerfile.dev
    ports :
    - 3000:3000
    volumes :
    - /usr/app/node_modules
    - .:/usr/app
